
export type TransactionType = 'INCOME' | 'EXPENSE';

export enum OSStatus {
  QUOTED = 'Orçado',
  APPROVED = 'Aprovado',
  IN_PROGRESS = 'Em Execução',
  FINISHED = 'Concluído',
  PAID = 'Pago'
}

export interface User {
  id: string;
  name: string;
  email: string;
  avatar: string;
}

export interface Transaction {
  id: string;
  type: TransactionType;
  amount: number;
  description: string;
  category: string;
  userId: string;
  userName: string;
  date: string;
  osId?: string;
}

export interface ProductItem {
  id: string;
  name: string;
  price: number;
  quantity: number;
}

export interface Quote {
  id: string;
  customerName: string;
  customerContact: string;
  items: ProductItem[];
  total: number;
  createdAt: string;
  status: 'PENDING' | 'APPROVED' | 'REJECTED';
}

export interface ServiceOrder {
  id: string;
  quoteId?: string;
  customerName: string;
  description: string;
  status: OSStatus;
  progress: number;
  createdAt: string;
  transactions: Transaction[];
}

export interface AppContextType {
  currentUser: User | null;
  users: User[];
  login: (userId: string) => void;
  logout: () => void;
  transactions: Transaction[];
  addTransaction: (t: Omit<Transaction, 'id' | 'userId' | 'userName'>) => void;
  serviceOrders: ServiceOrder[];
  // Fix: Omit createdAt from addOS parameters as it's generated by the context
  addOS: (os: Omit<ServiceOrder, 'id' | 'transactions' | 'progress' | 'createdAt'>) => void;
  updateOSStatus: (id: string, status: OSStatus) => void;
  quotes: Quote[];
  addQuote: (q: Omit<Quote, 'id' | 'createdAt' | 'status'>) => void;
  updateQuoteStatus: (id: string, status: Quote['status']) => void;
}